### ISSUE TITLE
Not working for VS2010 SP1 Ultimate + Windows 7 x64 Ultimate

### ISSUE THREAD

**Issue by imgen** [follesoe/VSMonoTouch#3] opened 2011-09-08 06:23 UTC
It's not working for VS2010 SP1 version. I have to manually change framework to 1.0 and even after that I get the 
Project file must include the .NET Framework assembly 'WindowsBase, PresentationCore, PresentationFramework' in the reference list

**Comment by follesoe** [comment] 2011-09-08 23:00
Thanks for reporting. Will try to reproduce the error - I have test on the same setup (VS2010 SP1 Ultimate + Win7 x64). Does it work if you do a "file new MonoTouch" project on Mac, and then open it on your Win machine? (I.e. try with a dead simple blank project vs. a perhaps more complete real project, just to narrow down the problem).

**Comment by imgen** [comment] 2011-09-09 00:56
The projects I tried are Miguel's Mono.Dialog and TweetStation project, both not VS2010 format. After conversion, I have to manually set the framework. 
Then I tried MonoMobile.Views, still I have to manually set the target framework.

**Comment by Lunat1k** [comment] 2011-09-12 10:58
I have the same setup and it works fine. Also You can ignore the warning. This is due to the xib files being marked as a page and VS looks for those assemblies when the compile mode is Page. I don't think he'll be able to get rid of that warning.

**Comment by imgen** [comment] 2011-09-13 10:54
For xib files, it will cause an error during building. Can u also make the manual  switch of target framework automated?

**Comment by Lunat1k** [comment] 2011-09-13 11:18
It will not error out on the builds. I actually keep both MonoDevelop and VS open at the same time and just code over a network share. Whenever I'm ready for it to build/debug I just flip over to the mac and run the debugger in MD. It won't interfear since it's just a warning. The only thing you have to do is make sure you reload the project in MD if you add new class files or reload it in VS if you add a new xib file in MD.

**Comment by robinbihun** [comment] 2011-09-23 18:39
I'm able to verify this error. Out of the box the project will not open. You have to remove the following line for it to work

&lt;ProjectTypeGuids&gt;{6BC8ED88-2882-458C-8E55-DFD12B67127B};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&lt;/ProjectTypeGuids&gt;

I did find this, http://msdn.microsoft.com/en-us/library/bb166537.aspx - if there is a way to register those guids in the registry it should be able to open without any modifications to the csproj file... in the meantime i'll just continue doing dev on the mac.

I should note: I am using MonoDevelop 2.8 beta on OSX Lion, VS 2010 Premium SP1 on Windows 7 Enterprise X64

**Comment by benoitjadinon** [comment] 2011-12-13 22:28
yup, same setup (win7 64, VS 2010, MD 2.8.4.2), same problem. 
it says "The C# project is targeting '.NetFramework,Version=1.0', which is not installed on this machine" and it is asking me to go online fetching the framework, or unloading the project.
after removing the <ProjectTypeGuids> line, I got the same message, but this time the project did not unload. (thx robbihun)

**Comment by Lunat1k** [comment] 2011-12-13 22:45
Sounds like you guys aren't following the instructions. But just a guess.

**Comment by benoitjadinon** [comment] 2011-12-13 22:53
looks like so. sorry about that.
who has the time to read readme's nowadays, right ? ;)

**Comment by follesoe** [comment] 2011-12-14 12:03
So the problem was not copying the assemblies into the v1.0 folder as described in readme?

raz-l do bring up an interesting point though - most people don't read readmes carefully enough to spot details like that. Perhaps the extension could scan for the existence of that folder and notify the user if it's missing and how to fix it - i.e a more friendly error message with hint on how to recover?

I'm closing this issue as the suggested behavior above is a new feature and not a bug related to machine config described in title.

**Closed as completed by follesoe** 2011-12-14 12:03 UTC
