### ISSUE TITLE
VS 2012 Support

### ISSUE THREAD

**Issue by dinonz** [follesoe/VSMonoTouch#13] opened 2012-08-15 23:05 UTC
Is this extension going to be updated for VS 2012?

**Comment by follesoe** [comment] 2012-08-16 09:04
That is the plan. I haven't had time to look into it yet - so feel free to create a VS2012 branch and work on it. If not I will try to port it to VS2012 later this fall.

**Comment by dinonz** [comment] 2012-08-16 18:36
Hi Jonas,

My experience with VS Extensions and with Git is pretty much nil, but I might look into it if I get some time. I’m presuming it needs a new project but the code should mostly copy over – I will play around and see what I can come up with.

Dino

**Comment by ste8** [comment] 2012-08-30 16:44
I published a "quick and dirty" upgrade to the extension that works in VS2012, or at least it works on my machine for my purposes. It is not to be intended as "final" solution, I just needed a quick solution and this works for me.

You can find it here: https://github.com/ste8/VSMonoTouch/tree/vs2012

**Comment by dinonz** [comment] 2012-08-30 17:01
Awesome – thank you!

Dino

**Comment by dinonz** [comment] 2012-09-02 15:27
Hey – I just tried it and it said project type was not supported – is there some addin I need to be able to develop VS.Net Extensions?

**Comment by follesoe** [comment] 2012-09-02 20:51
You need to download the Visual Studio 2010 / 2012 SDK - which adds the
project type needed to develop VS add-ins.

-Jonas

**Comment by slodge** [comment] 2012-09-25 11:40
Excellent :) Is there a prebuilt version of this available anywhere?

**Comment by slodge** [comment] 2012-09-25 11:46
Also wondered if anyone else was having problems with TargetFrameworkAttributeAttribute since installing VS2012

I've had to resort to adding this hack to my project files to keep them compiling: 

http://stackoverflow.com/questions/3104356/in-visual-studio-2010-why-is-the-netframework-version-v4-0-assemblyattributes-c

**Comment by delfuria** [comment] 2012-11-29 21:29
Hi,
i have build and installed the Dinoz workaround and all works fine.
If someone want to receive the vsix can send me an email and i'll send it.
Stefano

**Comment by slodge** [comment] 2012-11-29 21:56
Stefano
yes please. Lodge.stuart@gmail.com
thanks
stuart

**Comment by jlegan** [comment] 2012-12-12 07:17
Stefano,

Could I also get a copy?

Thanks,

Jim

**Comment by slodge** [comment] 2012-12-12 10:59
I've had a few requests now.... Hope it's OK with Stefano, but I've posted the VSIX copy sent to me to: http://sdrv.ms/U6FKrz

NOTE: Installing this is 100% at your own risk :)

**Comment by bryancostanich** [comment] 2012-12-13 14:11
is anyone having the issue where visual studio complains about the v1.0 framework not being installed, even though they copied in the MonoTouch assemblies to the /.NETFramework/v1.0/ folder, added the /RedistList/ folder and the FrameworkList.xml file? for some reason, i can't get it to work in windows 8, but it worked fine in windows 7.

**Comment by slodge** [comment] 2012-12-13 14:27
What's the exact error message?

... It feels like I've seen most error messages ;)

**Comment by theperm** [comment] 2012-12-13 17:47
I did but only because I had VS running when I created the ref libs. I 
checked it again after a reboot and it is now working fine.

**Comment by slodge** [comment] 2012-12-14 12:08
Since installing the VS2012 plugin lots of my operations have been really slow - especially in the larger mvvmcross solutions - e.g. creating a new Wpf project this morning took over 10 minutes :(

Anyone got any ideas what might be causing this? Or on what trace to enable to try to find out?

Any suggestions welcome. Thanks!

**Comment by theperm** [comment] 2012-12-14 15:28
Well, I get this from time to time, but it was before I installed the 
extension. My suggestion is to disable the extension to see if it is the 
cause, if not disable extensions one by and use a process of elimination 
to see if the cause is an extension.

I have seen this before and have no explanation as to why it occurs, 
because ive never been able to reproduce itintentionally. I do think my 
VS2012 is no where as fast as it was when I first installedit, but then 
it could be psychological, you get used to the speed, then it feels 
slowagain.

**Comment by rickduarte** [comment] 2012-12-29 15:29
Hey bryancostanich!

I solved my problem updating mono for android.
On VS2012, goto Tools -> Options -> Mono for Android, and then check for updates.

Hope it helps!

**Comment by slodge** [comment] 2012-12-29 17:15
The slow loading for mvx with vsmonotouch seems to be something to do with http://twitpic.com/bpmxk3

(from Oren on twitter)

anyone got any ideas what this might be? Or how to work around it?

I'm back on code tomorrow and will try 'stuff' until it works or until next year arrives...

**Comment by delfuria** [comment] 2013-01-02 15:38
Hi,
just as info, but when you try to create a new project what projects do you see under the "Mono Touch Flavor" ???
In my installation i have a lot of "strange" project's type.
Stefano

**Comment by slodge** [comment] 2013-01-11 22:01
Anyone who wants to help with reporting the slowness to Microsoft (it seems to be to do with the number of configurations), then you can run the same steps I'm going to - just to nudge MS along :)

> Greetings from Microsoft Connect!
> 
> This notification was generated for feedback item: <a href="http://connect.microsoft.com/VisualStudio/feedback/details/775466/really-slow-to-load-solutions-when-using-many-projects-with-many-profiles">Really slow to load solutions when using many projects with many profiles.</a> which you submitted at the <a href="http://connect.microsoft.com">Microsoft Connect</a> site.
> 
> Hello, to help us further investigate could you our feedback tool while opening the solution?
> 
> The feedback tool can be downloaded from http://visualstudiogallery.msdn.microsoft.com/f8a5aac8-0418-4f88-9d34-bdbe2c4cfe72
> 
> To use the tool:
> 1.       Install the feedback tool (restart VS)
> 2.       Load the solution
> 3.       Choose "Report Bug" on the help menu (login with Live ID)
> 4.       Choose existing feedback, and enter this bug number (775466)
> 5.       Choose "Performance" from feedback type
> 6.       Close the solution
> 7.       Open the solution
> 8.       Stop recording and submit the bug
> 
> Be sure to open the solution before choosing "Report Bug" to ensure we get details about the solution itself.
> 
> Thank you for your help.
> 
> You may receive a general "Feedback Item Updated" notification as well, if any other changes were made by Microsoft.
> 
> Thank you for using Microsoft Connect!

**Comment by rickduarte** [comment] 2013-01-11 22:07
Done.

**Comment by delfuria** [comment] 2013-01-11 22:10
HI Stuart,
 thanks for the suggestion.
 But only one question.
 How can we submit the report bug if the solution hangs visual studio ??
 Thanks in advance
 Stefano

----- Original Message -----

**Comment by slodge** [comment] 2013-01-11 22:22
It's not my feedback tool - I don't know the answer

Ask the question on that MS Connect issue?

**Comment by rickduarte** [comment] 2013-01-11 22:27
Go to the site:
http://connect.microsoft.com/VisualStudio/feedback/details/775466/really-slow-to-load-solutions-when-using-many-projects-with-many-profileswhich

Login
Then click on “Vote this as important”
After that, click on “I can too”, telling them that you can reproduce the bug too.

Best Regards,

Mario Henrique

**Comment by jmgomez** [comment] 2013-01-11 22:30
Thank you, done.

**Comment by follesoe** [comment] 2013-01-21 21:51
First of all - it's great to see that so many people find the VSMonoTouch project type useful - and is actively contributing in resolving issues etc :+1: 

I tried to look at the branch list - and there are several branches at different level. It would be great if some of you who has a reasonable stable branch with VS2012 support would issue a pull request to get the main branch updated.

I would also like some input weather or not we should simply tag the current head of the repo as VS2010, and make the master a VS2012 project type going forward - or should we try to support both VS2010 and VS2012? My gut feeling is that most MonoTouch developers are pretty "forward leaning" and is using the most current versions of VS. But please voice opinions to what you think.

Sorry for not taking an more active role in the project - but have been soaked in non MonoTouch work lately - but now it looks like I will be doing some MonoTouch again, so I would like to get an official built with updated documentation for VS2012 out the door.

**Comment by corliss** [comment] 2013-01-25 16:51
I'd highly suggest supporting both VS2010 and VS2012. Thanks!

**Comment by follesoe** [comment] 2013-02-12 11:14
Okay, no need to break backwards compatibility. So we'll keep VS2010 supported, but only support development in VS2012 (but the built extension will work in both 2010 and 2012). It is possible to maintain two sets of project and solution files to enable development on the extension in both 2010 and 2012, but I do not think it is worth the effort supporting both (development mode).

**Comment by follesoe** [comment] 2013-02-20 18:09
Development of VS2012 support is happening in the vs2012 branch.

**Comment by kentontaylor** [comment] 2013-08-01 13:56
With VS2012 Ultimate and VS2012 SDK, I am unable to compile this branch...see screenshot:
- http://cl.ly/image/2o3T022V321p

Am I missing something obvious?

Also, the downloadable .vsix file from this branch's readme appears to be the version for 2010...at least, it has the same filename, and throws the "not compatible" error when attempting to install:
- https://github.com/downloads/follesoe/VSMonoTouch/VSMonoTouch%201.2.vsix

**Closed as completed** 2020-11-09 12:24 UTC
Labels: Feature
